name: diabetes_app
description: Aplicativo mobile Flutter para controle de diabetes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Backend
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  
  # PDF Export (RF-10)
  pdf: ^3.10.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0
  intl: ^0.20.2
  
  # UI (From Remote)
  cupertino_icons: ^1.0.6
  forui: ^0.16.0

  # Profile Photo
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
